import UnityHubCommon

public extension Constant {
	enum Symbol {
		public static let cube: String = "cube"
		public static let tray: String = "tray"
		public static let info: String = "info"
		public static let info_circle: String = "info.circle"
		public static let pin: String = "pin"
		public static let pin_fill: String = "pin.fill"
		public static let folder: String = "folder"
		public static let questionMark: String = "questionmark"
		public static let magnifyingGlass: String = "magnifyingglass"
		public static let trash: String = "trash"
		public static let plus: String = "plus"
		public static let minus: String = "minus"
		public static let eye: String = "eye"
		public static let arrow_up_arrow_down: String = "arrow.up.arrow.down"
		public static let arrow_clockwise: String = "arrow.clockwise"
		public static let square_and_arrow_down: String = "square.and.arrow.down"
		public static let arrow_up: String = "arrow.up"
		public static let arrow_down: String = "arrow.down"
		public static let book_closed: String = "book.closed"
		public static let exclamationMark_triangle_fill: String = "exclamationmark.triangle.fill"
		public static let curlyBraces: String = "curlybraces"
		public static let person: String = "person"
		public static let person_3_sequence: String = "person.3.sequence"
		public static let cloud: String = "cloud"
		public static let gearShape: String = "gearshape"
		public static let ant: String = "ant"
		public static let ellipsis: String = "ellipsis"
		public static let arrow_up_forward: String = "arrow.up.forward"
		public static let list_bullet: String = "list.bullet"
		public static let checkmark: String = "checkmark"
		public static let externalDrive: String = "externaldrive"

		public static let finder: String = "finder"
		public static let ellipsis_vertical: String = "ellipsis.vertical"
		public static let rectangle_portrait_and_arrow_left: String = "rectangle.portrait.and.arrow.left"
	}
}
